### ISSUE TITLE
Look for rusoto alternatives

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/native-link#131]
Unfortunately rusoto is in "maintenance mode".

Fortunately, this only seems to affect `cas/store/s3_store.rs` and its tests.

It seems that https://github.com/awslabs/aws-sdk-rust could be a good alternative. That's also used by `attic`, which is basically turbo-cache for nix: https://github.com/zhaofengli/attic/blob/main/server/src/storage/s3.rs

**Comment by allada** [comment]
Yeah, I've been wanting to get off of rusoto for a while. I don't believe `aws-sdk-rust` existed when I first needed an s3 client. but yeah `aws-sdk-rust` is a good alternative, other people have suggested it to me.

**Comment by aaronmondal** [comment]
@allada If you're ok with it I'd like to work on this. My plan would be to replicate the existing functionality and tests and then attempt adding some integration tests that interact with a "real" bucket. I'll probably need to get turbo-cache running in k8s first, but a naive, non-cloud-native way seems fairly straightforward now that I got #178 working :relaxed:

Regarding integration tests, maybe we can get away with using something like [LocalStack](https://github.com/localstack/localstack) in CI?

**Comment by allada** [comment]
Yeah I'm super happy to have you take this.

For testing, I'd rather try to keep it all to unit tests until we have more users. Try not to focus much on getting tests to work with it, once we get a basic example working, I can go over it and see what the best strategy to test it is. If we need we can write a wrapper around the API calls we need to make and then mock out the implementation... but I'd like to avoid that if possible.

**Comment by chrisstaite-menlo** [comment]
We have a dependabot notification that "time" is vulnerable to a Segmentation Fault.  This crate is old required by "chrono" which is only required by "rusoto", since this is not maintained we have no way to fix this issue other than to move to an alternative crate for rusoto.

**Comment by allada** [comment]
Yeah this is on my todo list.
