### ISSUE TITLE
Errors should be forwarded to client if it could not execute command

### ISSUE THREAD

**Issue by allada** [TraceMachina/native-link#257]
Currently if a command cannot be executed on the worker the client is never notified and according to the client it hangs.

It is likely not passing the error code to the proper field.

**Comment by allada** [comment]
Reproduce with:

```
docker-compose up
```

```
bazel test //...   --remote_instance_name=main   --remote_cache=grpc://127.0.0.1:50051   --remote_executor=grpc://127.0.0.1:50052   --remote_default_exec_properties=cpu_count=1
```

but remove the PATH variable or make sure gcc or whatever is not present on the worker.

**Comment by TripleKai** [comment]
Hi @allada, @MarcusSorealheis, I'll try to resolve this one.
