### ISSUE TITLE
handle GB sized file uploads without OOM

### ISSUE THREAD

**Issue by lukts30** [TraceMachina/native-link#406]
CAS is unable to handle file uploads larger than the available RAM without encountering Out Of Memory (OOM) issues. When a 6GB file is uploaded, the `cas` process consumes around 10GB of RAM at its peak, preventing the upload of files larger than the installed RAM capacity.

I can see that it is already starts writing to a file as it receives the data but it seems like it still keeps the data in RAM until `finish_write=true` is received.

**Comment by aaronmondal** [comment]
Thanks, for this info. Could you post the configuration that you're using at the moment? There are many different store backends and the specific configuration is relevant to this issue.

**Comment by lukts30** [comment]
I have been using `cargo run --release --bin cas -- ./config/examples/basic_cas.json` with basic_cas.json edited from 10GB to a 50GB filesystem store.

I have just tried uploading a increasingly larger zero filled files (`fallocate -l 6GB large_file`).

**Comment by lukts30** [comment]
Until now my testing has primarily involved buck2. However, I can confirm that the same issue also occurs when using Bazel.

```
filegroup(
    name = "dataFiles",
    srcs = [
        "large_file"
    ],
)


genrule(
  name = "gen_data",
  srcs = [":dataFiles"],
  outs = ["data.txt"],
  cmd = "sha1sum $(SRCS) > $(OUTS) "
)
```

```
fallocate -l 5G large_file
bazel build :gen_data \
  --remote_instance_name=main \
  --remote_cache=grpc://127.0.0.1:50051 \
  --remote_executor=grpc://127.0.0.1:50051
```

**Comment by lukts30** [comment]
It also looks like after an action is executed during hashing the whole file is similarity kept in RAM. 
After a bazel clean and bazel build (with cache hit) this does not happen so download itself does not have OOM problem. 

```
genrule(
  name = "re_large_file",
  outs = ["re_large_file"],
  cmd = "fallocate -l 6G $(OUTS) "
)
bazel build :re_large_file    --remote_instance_name=main   --remote_cache=grpc://127.0.0.1:50051   --remote_executor=grpc://127.0.0.1:50051
```

**Comment by allada** [comment]
I think I see the issue. You are not using memory store, but memory store requires the entire payload to be received before evicting, which ends up bloating your memory.

I have created a fix here: #406

Can you checkout that branch try it? You'll also need to use the new `basic_cas.json` file, since it uses the new store.

**Comment by lukts30** [comment]
I can confirm that with that branch I am no longer getting any crashes. 

I can now upload a 40GB file to the remote as well as create a 40GB file on the remote and download that.

**Comment by allada** [comment]
Fixed: https://github.com/TraceMachina/native-link/commit/aea37682dbed261c401e5025ffd77dff2711f699
